# Generated by Django 3.0.5 on 2020-04-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField(null=True)),
                ('ename', models.CharField(max_length=500, null=True)),
                ('esal', models.IntegerField(null=True)),
                ('eaddr', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
